version: 0.2

phases:
  pre_build:
    commands:
      - echo pre_build
      - git clone https://${GIT_USER}:${GIT_PASS}@github.com/luizcoura/aws-pipeline.git
      - cd aws-pipeline
  build:
    commands:
      - docker build -t 775763617068.dkr.ecr.us-east-1.amazonaws.com/build-test:${CODEBUILD_BUILD_ID}
      - git branch -b release.${CODEBUILD_BUILD_ID}
      - git push origin release.${CODEBUILD_BUILD_ID}
  post_build:
    commands:
      - echo post_build
