version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: "775763617068"
    REPOSITORY_NAME: "build-test"
  parameter-store:
    GIT_USER: "gituser"
    GIT_PASS: "gitpass"

phases:
  pre_build:
    commands:
      # docker repository login
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)

      # git credentials 
      - echo "machine github.com" >> ~/.netrc
      - echo "login $GIT_USER" >> ~/.netrc
      - echo "password $GIT_PASS" >> ~/.netrc

      # clone repository
      - git clone https://github.com/luizcoura/aws-pipeline.git
      - cd aws-pipeline
  build:
    commands:
      # where the magic happens
      - bash build
  post_build:
    commands:
      - echo post_build
