version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo ${AWS_KEY}
      - printf "${AWS_KEY}\n${AWS_SEC}\n${AWS_REG}\n${AWS_OUT}\n" | aws configure --profile ${AWS_PRF}
      - $(aws ecr get-login --no-include-email --region ${AWS_REG} --profile ${AWS_PRF})
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t 545199448870.dkr.ecr.us-east-1.amazonaws.com/aws-pipeline:latest .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 545199448870.dkr.ecr.us-east-1.amazonaws.com/aws-pipeline:latest
